services:
  marina:
    build: .
    volumes:
      - marina-data:/out:Z #docker volume

  ngrok:
    image: ngrok/ngrok:3
    command: ["http", "marina:5000"]
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
volumes:
  marina-data:
#managed volumes