FROM python:3.12-slim

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY server.py .

#binary already Compiled OCalm ./marina
RUN pip install flask

# Create bin directory
RUN mkdir -p /app/bin

EXPOSE 5000

CMD ["python", "server.py"]


